# Delete these routes and define your own shop routes here

dedi_sylius_sag_static_welcome:
    path: /static-welcome/{name}
    defaults:
        _controller: Dedi\SyliusSAGPlugin\Controller\GreetingController::staticallyGreetAction
        name: ~

dedi_sylius_sag_dynamic_welcome:
    path: /dynamic-welcome/{name}
    defaults:
        _controller: Dedi\SyliusSAGPlugin\Controller\GreetingController::dynamicallyGreetAction
        name: ~
