sylius_ui:
    events:
        sylius.shop.layout.stylesheets:
            blocks:
                dedi_sag_styles: '@DediSyliusSAGPlugin/Shop/_styles.html.twig'

        sylius.shop.layout.footer:
            blocks:
                dedi_sag_widget_reassurance: '@DediSyliusSAGPlugin/Shop/Layout/Footer/_reassurance.html.twig'
                dedi_sag_widget_footer: '@DediSyliusSAGPlugin/Shop/Layout/Footer/_widgetFooter.html.twig'

        sylius.shop.layout.javascripts:
            blocks:
                dedi_sag_widget_global: '@DediSyliusSAGPlugin/Shop/Layout/_widgetGlobal.html.twig'
                dedi_sag_script: '@DediSyliusSAGPlugin/Shop/_scripts.html.twig'

        sylius.shop.product.show.tab_reviews:
            blocks:
                statistics:
                    template: '@DediSyliusSAGPlugin/Shop/Product/Show/Tabs/Reviews/_statistics.html.twig'
                    priority: 40
                create:
                    enabled: false

        sylius.shop.product_review.index.list:
            blocks:
                statistics:
                    template: '@DediSyliusSAGPlugin/Shop/ProductReview/_statistics.html.twig'
                    priority: 30
                dedi_sag_pagination:
                    template: '@DediSyliusSAGPlugin/Shop/ProductReview/_pagination.html.twig'
                    priority: 5

                add_button:
                    enabled: false

        sylius.admin.channel.create.form:
            blocks:
                dedi_sag_configuration:
                    template: '@DediSyliusSAGPlugin/Admin/Channel/_configuration.html.twig'
                    priority: 20

        sylius.admin.channel.update.form:
            blocks:
                dedi_sag_configuration:
                    template: '@DediSyliusSAGPlugin/Admin/Channel/_configuration.html.twig'
                    priority: 20

        sylius.admin.product.create.tab_details:
            blocks:
                dedi_sag_identificiation:
                    template: '@DediSyliusSAGPlugin/Admin/Product/_identificationForm.html.twig'
                    priority: 20

        sylius.admin.product.update.tab_details:
            blocks:
                dedi_sag_identificiation:
                    template: '@DediSyliusSAGPlugin/Admin/Product/_identificationForm.html.twig'
                    priority: 20
