sylius_grid:
    grids:
        dedi_sylius_sag_plugin_api_key_config:
            driver:
                name: doctrine/orm
                options:
                    class: Dedi\SyliusSAGPlugin\Entity\ApiKeyConfig
            fields:
                countryCode:
                    label: dedi_sylius_sag_plugin.ui.country_code
                    type: twig
                    options:
                        template: '@DediSyliusSAGPlugin/Admin/Common/Grid/Field/SAGCountryCode.html.twig'
                apiKey:
                    label: dedi_sylius_sag_plugin.ui.api_key
                    type: string
                certificateOfTruthUrl:
                    label: dedi_sylius_sag_plugin.ui.certificate_of_truth_url
                    type: twig
                    options:
                        template: '@DediSyliusSAGPlugin/Admin/ApiKeyConfig/Grid/Field/certificateOfTruthUrl.html.twig'
                locales:
                    label: sylius.ui.locales
                    type: twig
                    options:
                        template: '@DediSyliusSAGPlugin/Admin/ApiKeyConfig/Grid/Field/locales.html.twig'
                channels:
                    label: sylius.ui.channels
                    type: twig
                    options:
                        template: '@DediSyliusSAGPlugin/Admin/ApiKeyConfig/Grid/Field/channels.html.twig'
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete

        sylius_admin_product_review:
            fields:
                SAGId:
                    type: twig
                    label: dedi_sylius_sag_plugin.ui.sag_id
                    position: 0
                    options:
                        template: '@DediSyliusSAGPlugin/Admin/ProductReview/Grid/Field/SAGId.html.twig'
                comment:
                    label: sylius.ui.comment
                    type: string
                SAGAnswerComment:
                    label: dedi_sylius_sag_plugin.ui.answer_comment
                    type: string
                SAGAnswerCreatedAt:
                    label: dedi_sylius_sag_plugin.ui.answer_created_at
                    type: datetime
                SAGOrderedAt:
                    label: dedi_sylius_sag_plugin.ui.ordered_at
                    type: datetime
                SAGCountryCode:
                    label: dedi_sylius_sag_plugin.ui.country_code
                    type: twig
                    options:
                        template: '@DediSyliusSAGPlugin/Admin/Common/Grid/Field/SAGCountryCode.html.twig'
                author:
                    label: sylius.ui.author
                    type: twig
                    options:
                        template: '@DediSyliusSAGPlugin/Admin/ProductReview/Grid/Field/author.html.twig'
                title:
                    enabled: false

            filters:
                rating:
                    label: sylius.ui.rating
                    type: select
                    form_options:
                        choices:
                            0: 0
                            1: 1
                            2: 2
                            3: 3
                            4: 4
                            5: 5
                SAGCountryCode:
                    label: dedi_sylius_sag_plugin.ui.country_code
                    type: string
                createdAt:
                    label: sylius.ui.created_at
                    type: date
                SAGAnswerCreatedAt:
                    label: dedi_sylius_sag_plugin.ui.answer_created_at
                    type: date
                title:
                    enabled: false

            actions:
                item:
                    update:
                        enabled: false
                    accept:
                        enabled: false
                    reject:
                        enabled: false
                    delete:
                        enabled: false
                bulk:
                    delete:
                        enabled: false
